export const students = [
  {
    id: "1",
    facultyId: "1",
    facultyName: "Engineering",
    classId: "1",
    className: "Computer Science - Semester 1",
    name: "John Doe",
    gender: "Male",
    parentPhone: "+1234567890",
    phone: "+1234567891",
    studentId: "ENG001",
    passcode: "1234",
    status: "active",
  },
  {
    id: "2",
    facultyId: "1",
    facultyName: "Engineering",
    classId: "2",
    className: "Electrical Engineering - Semester 2",
    name: "Jane Smith",
    gender: "Female",
    parentPhone: "+1234567892",
    phone: "+1234567893",
    studentId: "ENG002",
    passcode: "1234",
    status: "active",
  },
  {
    id: "3",
    facultyId: "2",
    facultyName: "Business",
    classId: "3",
    className: "Marketing - Semester 3",
    name: "Bob Johnson",
    gender: "Male",
    parentPhone: "+1234567894",
    phone: "+1234567895",
    studentId: "BUS001",
    passcode: "1234",
    status: "inactive",
  },
  {
    id: "4",
    facultyId: "2",
    facultyName: "Business",
    classId: "4",
    className: "Finance - Semester 4",
    name: "Alice Brown",
    gender: "Female",
    parentPhone: "+1234567896",
    phone: "+1234567897",
    studentId: "BUS002",
    passcode: "1234",
    status: "active",
  },
  {
    id: "5",
    facultyId: "3",
    facultyName: "Medicine",
    classId: "5",
    className: "Nursing - Semester 1",
    name: "Charlie Wilson",
    gender: "Other",
    parentPhone: "+1234567898",
    phone: "+1234567899",
    studentId: "MED001",
    passcode: "1234",
    status: "active",
  },
]

export const courses = [
  {
    id: "1",
    departmentId: "1",
    departmentName: "Computer Science",
    courseName: "Introduction to Programming",
    code: "CS101",
    semester: 1,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "2",
    departmentId: "1",
    departmentName: "Computer Science",
    courseName: "Data Structures",
    code: "CS201",
    semester: 2,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "3",
    departmentId: "2",
    departmentName: "Electrical Engineering",
    courseName: "Circuit Analysis",
    code: "EE101",
    semester: 1,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "4",
    departmentId: "3",
    departmentName: "Marketing",
    courseName: "Marketing Principles",
    code: "MKT101",
    semester: 1,
    facultyId: "2",
    facultyName: "Business",
  },
  {
    id: "5",
    departmentId: "4",
    departmentName: "Finance",
    courseName: "Financial Accounting",
    code: "FIN101",
    semester: 1,
    facultyId: "2",
    facultyName: "Business",
  },
]

export const examTypes = [
  {
    id: "1",
    name: "midterm",
    marks: 30,
    description: "Mid-semester examination",
  },
  {
    id: "2",
    name: "final",
    marks: 50,
    description: "End of semester examination",
  },
  {
    id: "3",
    name: "quiz",
    marks: 10,
    description: "Regular class quiz",
  },
]
