export const students = [
  {
    id: "1",
    facultyId: "1",
    facultyName: "Engineering",
    classId: "1",
    className: "Computer Science - Semester 1",
    name: "John Doe",
    gender: "Male",
    parentPhone: "+1234567890",
    phone: "+1234567891",
    studentId: "ENG001",
    passcode: "1234",
    status: "active",
  },
  {
    id: "2",
    facultyId: "1",
    facultyName: "Engineering",
    classId: "2",
    className: "Electrical Engineering - Semester 2",
    name: "Jane Smith",
    gender: "Female",
    parentPhone: "+1234567892",
    phone: "+1234567893",
    studentId: "ENG002",
    passcode: "1234",
    status: "active",
  },
  {
    id: "3",
    facultyId: "2",
    facultyName: "Business",
    classId: "3",
    className: "Marketing - Semester 3",
    name: "Bob Johnson",
    gender: "Male",
    parentPhone: "+1234567894",
    phone: "+1234567895",
    studentId: "BUS001",
    passcode: "1234",
    status: "inactive",
  },
  {
    id: "4",
    facultyId: "2",
    facultyName: "Business",
    classId: "4",
    className: "Finance - Semester 4",
    name: "Alice Brown",
    gender: "Female",
    parentPhone: "+1234567896",
    phone: "+1234567897",
    studentId: "BUS002",
    passcode: "1234",
    status: "active",
  },
  {
    id: "5",
    facultyId: "3",
    facultyName: "Medicine",
    classId: "5",
    className: "Nursing - Semester 1",
    name: "Charlie Wilson",
    gender: "Other",
    parentPhone: "+1234567898",
    phone: "+1234567899",
    studentId: "MED001",
    passcode: "1234",
    status: "active",
  },
]

export const courses = [
  {
    id: "1",
    departmentId: "1",
    departmentName: "Computer Science",
    courseName: "Introduction to Programming",
    code: "CS101",
    semester: 1,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "2",
    departmentId: "1",
    departmentName: "Computer Science",
    courseName: "Data Structures",
    code: "CS201",
    semester: 2,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "3",
    departmentId: "2",
    departmentName: "Electrical Engineering",
    courseName: "Circuit Analysis",
    code: "EE101",
    semester: 1,
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "4",
    departmentId: "3",
    departmentName: "Marketing",
    courseName: "Marketing Principles",
    code: "MKT101",
    semester: 1,
    facultyId: "2",
    facultyName: "Business",
  },
  {
    id: "5",
    departmentId: "4",
    departmentName: "Finance",
    courseName: "Financial Accounting",
    code: "FIN101",
    semester: 1,
    facultyId: "2",
    facultyName: "Business",
  },
]

export const examTypes = [
  {
    id: "1",
    name: "midterm",
    marks: 30,
    description: "Mid-semester examination",
  },
  {
    id: "2",
    name: "final",
    marks: 50,
    description: "End of semester examination",
  },
  {
    id: "3",
    name: "quiz",
    marks: 10,
    description: "Regular class quiz",
  },
]

export const attendanceData = [
  {
    id: "1",
    studentId: "1",
    classId: "1",
    courseId: "1",
    userId: "1",
    date: "2024-01-15",
    isPresent: true,
  },
  {
    id: "2",
    studentId: "1",
    classId: "1",
    courseId: "1",
    userId: "1",
    date: "2024-01-16",
    isPresent: false,
  },
  {
    id: "3",
    studentId: "2",
    classId: "2",
    courseId: "2",
    userId: "1",
    date: "2024-01-15",
    isPresent: true,
  },
  {
    id: "4",
    studentId: "2",
    classId: "2",
    courseId: "2",
    userId: "1",
    date: "2024-01-16",
    isPresent: true,
  },
  {
    id: "5",
    studentId: "3",
    classId: "3",
    courseId: "4",
    userId: "1",
    date: "2024-01-15",
    isPresent: false,
  },
]

export const examData = [
  {
    id: "1",
    studentId: "1",
    courseId: "1",
    examTypeId: "1",
    marksObtained: 25,
    date: "2024-01-20",
    userId: "1",
  },
  {
    id: "2",
    studentId: "1",
    courseId: "1",
    examTypeId: "2",
    marksObtained: 42,
    date: "2024-02-15",
    userId: "1",
  },
  {
    id: "3",
    studentId: "2",
    courseId: "2",
    examTypeId: "1",
    marksObtained: 28,
    date: "2024-01-20",
    userId: "1",
  },
  {
    id: "4",
    studentId: "2",
    courseId: "2",
    examTypeId: "3",
    marksObtained: 8,
    date: "2024-01-25",
    userId: "1",
  },
  {
    id: "5",
    studentId: "3",
    courseId: "4",
    examTypeId: "1",
    marksObtained: 22,
    date: "2024-01-20",
    userId: "1",
  },
]

export const feeData = [
  {
    id: "1",
    studentId: "1",
    financeType: "tuition",
    amount: 5000,
    amountPaid: 5000,
    balance: 0,
    status: "paid",
    dueDate: "2024-01-31",
  },
  {
    id: "2",
    studentId: "1",
    financeType: "registration",
    amount: 500,
    amountPaid: 300,
    balance: 200,
    status: "partial",
    dueDate: "2024-02-15",
  },
  {
    id: "3",
    studentId: "2",
    financeType: "tuition",
    amount: 5000,
    amountPaid: 0,
    balance: 5000,
    status: "unpaid",
    dueDate: "2024-01-31",
  },
  {
    id: "4",
    studentId: "2",
    financeType: "library",
    amount: 200,
    amountPaid: 200,
    balance: 0,
    status: "paid",
    dueDate: "2024-01-15",
  },
  {
    id: "5",
    studentId: "3",
    financeType: "tuition",
    amount: 4500,
    amountPaid: 2000,
    balance: 2500,
    status: "partial",
    dueDate: "2024-01-31",
  },
]

export const classes = [
  {
    id: "1",
    name: "Computer Science - Semester 1",
    departmentId: "1",
    departmentName: "Computer Science",
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "2",
    name: "Electrical Engineering - Semester 2",
    departmentId: "2",
    departmentName: "Electrical Engineering",
    facultyId: "1",
    facultyName: "Engineering",
  },
  {
    id: "3",
    name: "Marketing - Semester 3",
    departmentId: "3",
    departmentName: "Marketing",
    facultyId: "2",
    facultyName: "Business",
  },
  {
    id: "4",
    name: "Finance - Semester 4",
    departmentId: "4",
    departmentName: "Finance",
    facultyId: "2",
    facultyName: "Business",
  },
  {
    id: "5",
    name: "Nursing - Semester 1",
    departmentId: "5",
    departmentName: "Nursing",
    facultyId: "3",
    facultyName: "Medicine",
  },
]
